"""Generate a private C++ header from the workspace .env file.

The generated header lives under .pio/ (gitignored), so MQTT credentials never
become source-controlled build flags or firmware source files.
"""

Import("env")

import json
import os
from pathlib import Path


PROJECT_DIR = Path(env.subst("$PROJECT_DIR"))
WORKSPACE_DIR = PROJECT_DIR.parent


def parse_dotenv(path):
    values = {}
    if not path.exists():
        return values

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        values[key] = value
    return values


file_values = parse_dotenv(WORKSPACE_DIR / ".env")


def setting(*names, default=None):
    for name in names:
        value = os.environ.get(name) or file_values.get(name)
        if value:
            return value
    return default


secrets = {
    "HIVEMQ_HOST": setting("SECRET_HIVEMQ_HOST", "HIVEMQ_HOST"),
    "HIVEMQ_TCP_PORT": setting(
        "SECRET_HIVEMQ_TCP_PORT", "HIVEMQ_PORT", default="8883"
    ),
    "MQTT_USERNAME": setting(
        "SECRET_ESP32_MQTT_USERNAME", "SECRET_MQTT_USERNAME", "MQTT_USER"
    ),
    "MQTT_PASSWORD": setting(
        "SECRET_ESP32_MQTT_PASSWORD", "SECRET_MQTT_PASSWORD", "MQTT_PASS"
    ),
    "MQTT_TOPIC_PREFIX": setting(
        "SECRET_MQTT_TOPIC_PREFIX",
        "MQTT_TOPIC_PREFIX",
        default="smartmirror/team01",
    ),
}

missing = [
    key
    for key in ("HIVEMQ_HOST", "MQTT_USERNAME", "MQTT_PASSWORD")
    if not secrets[key]
]
if missing:
    raise RuntimeError(
        "Missing firmware settings: "
        + ", ".join(missing)
        + ". Copy ../.env.example to ../.env and fill in HiveMQ credentials."
    )

try:
    tcp_port = int(secrets["HIVEMQ_TCP_PORT"])
except ValueError as error:
    raise RuntimeError("HIVEMQ TCP port must be an integer") from error

if tcp_port != 8883:
    raise RuntimeError("Security policy only permits HiveMQ MQTT/TLS port 8883")

topic_prefix = secrets["MQTT_TOPIC_PREFIX"].strip("/")
if not topic_prefix or any(char in topic_prefix for char in ("+", "#", " ")):
    raise RuntimeError("MQTT topic prefix must be non-empty and contain no +, # or spaces")

generated_dir = PROJECT_DIR / ".pio" / "generated"
generated_dir.mkdir(parents=True, exist_ok=True)
header_path = generated_dir / "generated_secrets.h"
header_content = "\n".join(
    [
        "#pragma once",
        "",
        "// Generated by scripts/load_env.py. Do not commit or print this file.",
        f"#define HIVEMQ_HOST {json.dumps(secrets['HIVEMQ_HOST'])}",
        f"#define HIVEMQ_TCP_PORT {tcp_port}",
        f"#define MQTT_USERNAME {json.dumps(secrets['MQTT_USERNAME'])}",
        f"#define MQTT_PASSWORD {json.dumps(secrets['MQTT_PASSWORD'])}",
        f"#define MQTT_TOPIC_PREFIX {json.dumps(topic_prefix)}",
        "",
    ]
)

if not header_path.exists() or header_path.read_text(encoding="utf-8") != header_content:
    header_path.write_text(header_content, encoding="utf-8")

env.Append(CPPPATH=[str(generated_dir)])
